#!/bin/bash

# Forma de uso:
#
#         perfctr <CORE_ID> <GRUPO_PERFORMANCE> ./matmult <opcoe_matmult>
#
# Exemplo, para fazer as medições de performance de FLOPS_DP no core 3
#
#         perfctr 3 FLOPS_DP ./matmult -n 64
#
# ---- parte Modificada ---- 
LIKWID_CMD="likwid-perfctr -O -C 3 -g $1 -m" 
shift 2

echo "performance" > /sys/devices/system/cpu/cpufreq/policy3/scaling_governor

make

for SIZE in 64
do
	python3 gera_entrada $SIZE | ${LIKWID_CMD} ./matmult > ./Resultados/$1_$SIZE.txt
done

make purge

echo "powersave" > /sys/devices/system/cpu/cpufreq/policy3/scaling_governor
# ---------------------------
# Para obter topologia dos cpu's
#      likwid-topology -c -g

# Para obter lista de grupos de indicadores de performance:
#      likwid-perfctr -a

# Para obter lista de Eventos e Contadores
#      likwid-perfctr -e

